### ISSUE TITLE
Manticore issue in this artifact

### ISSUE THREAD

**Issue by fang19911030** [SoftSec-KAIST/Smartian-Artifact#1]
I am trying to reproduce this result, but I have some issues to execute manticore in the docker. Could you have a look or give me some suggestions? Thank you.
```
Contract name: ExtremeToken
Creating EVM object...
Registering detector modules...
Adding filters...
Creating accounts...
Traceback (most recent call last):
  File "/home/test/scripts/run_manticore.py", line 170, in <module>
    main(timeout, src, name, benchmark)
  File "/home/test/scripts/run_manticore.py", line 115, in main
    m, detectors, user_account, contract_account = create_EVM(src, name, benchmark)
  File "/home/test/scripts/run_manticore.py", line 69, in create_EVM
    contract_account = m.solidity_create_contract(src, owner=user_account, contract_name=name)
  File "/home/test/tools/manticore/venv/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 576, in solidity_create_contract
    source_code, contract_name_i, libraries=deps, crytic_compile_args=compile_args
  File "/home/test/tools/manticore/venv/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 350, in _compile
    source_code, contract_name, libraries, crytic_compile_args
  File "/home/test/tools/manticore/venv/lib/python3.6/site-packages/manticore/ethereum/manticore.py", line 305, in _compile_through_crytic_compile
    filename = compilation_unit.filename_of_contract(name).absolute
AttributeError: 'CompilationUnit' object has no attribute 'filename_of_contract'
```

**Comment by jchoi2022** [comment]
This seems to be an issue reported in Manticore repository ([link](https://github.com/trailofbits/manticore/issues/2519)). Since the PIP library environment is continuously updated, the same code may suddenly stop to work at certain point. In fact, Manticore repository had declared to stop its active maintenance, so we believe this kind of issue will persist to occur. Because of this, we are planning to remove Manticore from the comparison target if we update this repository later.
